name: Thumos Mindfulness
favicon: null
layout_spectrum: 0.25059
typography_spectrum: 0.60469
title: 'Thumos Mindfulness & Psychotherapy'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d9d2c0'
    - '#455151'
    - '#999a92'
    - '#5e6a6a'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
